Special case `quote!`/`quote_spanned!` for 1 and 2 tts.
dtolnay/quote pull request #217
Opened 2022-04-07 23:30 UTC by nnethercote

These make crates that use `quote` compile faster.

I also tried specializing for 3 tts, but the rules are more complex and
the additional perf wins are much smaller than they are for 1 and 2 tts.

2022-04-07 23:33 UTC, nnethercote commented
Some instruction counts results for non-incremental `cargo check` builds on some crates that use `quote` heavily.

Benchmark | Profile | Scenario | % Change | Significance Factor?
-- | -- | -- | -- | --
ctor-0.1.21 | check | full | -12.39% | 61.93x
num-derive-0.3.3 | check | full | -11.05% | 55.26x
pest_generator-2.1.3 | check | full | -11.02% | 55.11x
enum-as-inner-0.4.0 | check | full | -9.73% | 48.67x
mockall_derive-0.11.0 | check | full | -6.63% | 33.17x
futures-macro-0.3.19 | check | full | -5.82% | 29.12x
wasm-bindgen-backend-0.2.79 | check | full | -4.44% | 22.20x
wayland-scanner-0.29.4 | check | full | -3.75% | 18.75x
pyo3-macros-backend-0.16.3 | check | full | -2.37% | 11.83x
tonic-build-0.7.0 | check | full | -2.34% | 11.68x
clap_derive-3.1.7 | check | full | -2.16% | 10.78x
prost-derive-0.10.0 | check | full | -2.16% | 10.78x
ref-cast-impl-1.0.6 | check | full | -1.95% | 9.74x
diesel_derives-1.4.1 | check | full | -1.84% | 9.20x
stdweb-derive-0.5.3 | check | full | -1.58% | 7.88x
vsdb_derive-0.21.1 | check | full | -1.01% | 5.05x

2022-04-11 03:23 UTC, dtolnay requested changes

2022-04-11 03:23 UTC, dtolnay commented on src/lib.rs
> +        let _: $crate::__private::Span = $span;
`$span` is missing from the macro argument list.

2022-04-11 03:23 UTC, dtolnay commented on src/lib.rs
> +        $crate::quote_token_spanned!($tt _span _s);
`_span` is not defined. You need to change the previous line to assign `_span`.

2022-04-11 03:25 UTC, dtolnay reviewed
Thanks, this looks promising.

The failing ui test should be fixed if you rebase past 31c3be473d0457e29c4f47ab9cff73498ac804a7. Rustc's diagnostics sometimes change.

2022-04-11 03:48 UTC, nnethercote commented
CI gets one test error, but I get two locally -- the second one in `tests/ui/not-repeatable.stderr`. Not sure why. I have pushed a new version that updates the expected output just for `tests/ui/not-quotable.rs`. Hopefully that'll be enough to satisfy CI.

2022-04-11 03:53 UTC, nnethercote commented
Whoops, no, I pushed a version with both test changes. This time it should just be the one change.

2022-04-11 03:58 UTC, dtolnay approved these changes
Thanks!

2022-04-11 03:58 UTC, merged